Linaro/qa-reports-known-issues

ltp-production.yaml

To populate the set of LKFT LTP known issues in qa-reports the file
ltp-production.yaml is been updated with known failed test cases.
These set of tests fails and exit cleanly.
The test cases which cause kernel crash / hangs the system are still in
test-definitions/automated/linux/ltp/skipfile-lkft.yaml file

LTP: updating known failed test cases list for qa-reports

---

kselftests-production.yaml

To populate the set of LKFT kselftests known issues in qa-reports the
file kselftests-production.yaml is been created with known failed tests.
These set of tests fails and exit cleanly.
The test cases which cause kernel crash / hangs the system are still in
test-definitions/automated/linux/kselftest/skipfile-lkft.yaml file

kselftests: updating known failed test cases list for qa-reports

---

kselftests-production.yaml

Change the name from "kselftests" to "kselftest" because it should
match with test suite name.

LKFT: kselftest: match with test suite name

---

ltp-production.yaml

LKFT: LTP fs read_all_sys fails intermittently on hikey

---

ltp-production.yaml

These 2 commits updates LTP known issues for bugs 4023 and 4024.
Link: https://bugs.linaro.org/show_bug.cgi?id=4023
Link: https://bugs.linaro.org/show_bug.cgi?id=4024
Signed-off-by: Rafael David Tinoco <rafael.tinoco@linaro.org>

Updates LTP known issues for bugs 4023 and 4024

---

kselftests-production.yaml

Adding rseq tests as known issues for older kernels for all devices.
- 4.14
- 4.9
- 4.4

LKFT: kselftest: rseq: Function not implemented on older kernel

---

ltp-production.yaml

LTP 20180926 tested on all branches and identified known failures
are added as known xfail.
List of test:
- ltp-syscalls-tests/bind03
- ltp-syscalls-tests/mlock203
- ltp-syscalls-tests/keyctl05
- ltp-syscalls-tests/execveat03
- ltp-syscalls-tests/statx04
- ltp-syscalls-tests/fgetxattr02
- ltp-syscalls-tests/fsetxattr02
- ltp-cve-tests/cve-2014-0196

LTP-20180926: Adding ltp release testing failures to xfails

---

LICENSE
Makefile
README.md
kselftests-production.yaml
sync_known_issues.py

Use raise_for_status() to fail for any http request that contains
errors. This eliminates a bunch of error handling code.
Add an assert to ensure some environments are found. There are some
known issue definitions that had invalid environments listed, which
resulted in them not being applied as anticipated. This has also been
fixed.
Signed-off-by: Dan Rue <dan.rue@linaro.org>

Make requests calls more strict

---

kselftests-production.yaml

kselftests: Adding xfails for kselftest vsyscall mode {native|none} tests

---

kselftests-production.yaml

kselftest case lib prints.sh getting PASS on all branches now.
So Removing lib_printf.sh from known issues list.

kselftests: Remove lib_printf.sh from xfail list

---

kselftests-production.yaml

kselftests: proc-self-map-files-001 wont run for any ARM env.
Signed-off-by: Rafael David Tinoco <rafael.tinoco@linaro.org>

kselftests: proc-self-map-files-001 wont run for any ARM env.

---

ltp-production.yaml

The CVE is x86_64 related only:
"""
If an NMI returns via espfix64 and is interrupted during espfix64 setup
by another NMI, the return state is corrupt.  This is exploitable for
reliable privilege escalation on any Linux x86_64 system in which
untrusted code can arrange for espfix64 to be invoked and for NMIs to be
nested.
"""
And it seems to be passing in almost every test run (there was 1 failure
here and there for x86_64). During a lkft-triage review meeting we
agreed that we shouldn't focus in this particular test since it is
testing a particular way of corrupting the x86_64 (only) NMI handler
when there are nested NMIs coming from userland.
Signed-off-by: Rafael David Tinoco <rafael.tinoco@linaro.org>

LTP: cve-2015-3290 should be skipped in all environments

---

ltp-production.yaml
spectre-meltdown-checker.yaml

The test suite spectre meltdown checker few test cases are getting failed
Here is the list of tests adding to known issues list.
- CVE-2018-3639
- CVE-2018-3640
- CVE-2018-3615
- CVE-2018-3620
- CVE-2017-5754

known-issues: Adding spectre-meltdown-checker known issues list

---

kselftests-production.yaml

kselftest: proc read as intermittent known failure on vsyscall modes

---

ltp-production.yaml
test_data/test-issues-2.yaml
test_sync_known_issues.py

LTP: dio: dio13 No space left on device
This is a limitation of qemu_arm32 so marking this as known issue.
ltp-dio-tests/dio13
Ref:
https://bugs.linaro.org/show_bug.cgi?id=4304

LTP: Adding dio13 as known issue on qemu_arm

---

ltp-production.yaml

Adding LTP fs quota_remount_test01 as known failure to qemu_x86_64 and
qemu_i386. And this is an intermittent failure.

ltp: Adding quota_remount_test01 to qemu_x86_64 and qemu_i386

---

ltp-production.yaml
spectre-meltdown-checker.yaml

Adding following test cases as intermittent failures,
- cve-2017-17053
- CVE-2018-3615
- clock_nanosleep02

known issues: update LTP and spectre meltdown intermittent failures

---

ltp-production.yaml

LTP: Adding known test failure cve-2017-17053 to all qemu's and i386

---

ltp-production.yaml

As a part of LTP upgrade to LTP 20190517 version the following tests
have been identified as failed and adding them to knonw issues list
- ltp-io-tests/aio02
- ltp-syscalls-tests/ioctl_ns05
- ltp-syscalls-tests/ioctl_ns06
- ltp-syscalls-tests/acct01
- ltp-syscalls-tests/pwritev201
- ltp-syscalls-tests/pwritev201_64
ref:
https://bugs.linaro.org/show_bug.cgi?id=5295
https://bugs.linaro.org/show_bug.cgi?id=5296
https://bugs.linaro.org/show_bug.cgi?id=5297
https://bugs.linaro.org/show_bug.cgi?id=5298

LTP-20190517: new test failures and adding them to known issues

---

kselftests-production.yaml

When kselftest upgrade to 5.1 we have noticed these two tests getting PASS.
So Remove them from XFAIL list.
- test_libbpf.sh
- test_offload.py
For test_tcpbpf_user the failure description and bug link updated.

kselftests: Remove XFAIL on test_libbpf.sh and test_offload.py

---

kselftests-production.yaml

Adding test_tcpnotify_user as XFAIL for
all 32bit for all branches
all devices for 4.19, 4.14, 4.9 and 4.4
- environments: *environments_32bit
projects: *projects_all
- environments: *environments_all
projects:
- lkft/linux-stable-rc-4.19-oe
- lkft/linux-stable-rc-4.14-oe
- lkft/linux-stable-rc-4.9-oe
- lkft/linux-stable-rc-4.4-oe
- lkft/linaro-hikey-stable-rc-4.4-oe

kselftests: Adding test_tcpnotify_user to old kernel branches

---

kselftests-production.yaml
ltp-production.yaml

kselftests: Adding x86_64 and i386 for kvm test failures

---

ltp-production.yaml

LTP syscalls test case sync_file_range02  failed while testing for
ext4 on Hikey, dragonboard 410c, x15 and qemu_arm.
ref:
https://bugs.linaro.org/show_bug.cgi?id=5472

LTP: Adding sync_file_range02 as known intermittent failure

---

ltp-production.yaml

LTP: Adding mtest06 as known intermittent failure on all environments

---

perf.yaml

Following test cases Added as known perf failure list
- perf/perf_record_test
- perf/perf_report_test
- perf/Object-code-reading
- perf/Read-backward-ring-buffer

perf: Adding known failures list

---

kselftests-production.yaml

kselftests: Adding pidfd_test as known intermittent issue

---

ltp-production.yaml

LTP: Adding open posix schedule_1-1 as known intermittent failure

---

kselftests-production.yaml

The following tests added as known failures
- pidfd_pidfd_open_test
- pidfd_pidfd_poll_test
- net_traceroute.sh
- net_tcp_fastopen_backup_key.sh
Ref:
https://bugs.linaro.org/show_bug.cgi?id=5530
https://bugs.linaro.org/show_bug.cgi?id=5531
https://bugs.linaro.org/show_bug.cgi?id=5532

kselftests: Adding known failure list

---

kselftests-production.yaml

kselftests: Adding seccomp_benchmark as intermittent failure

---

kselftests-production.yaml

The typo issue fixed
net tcp_fastopen_backup_key.sh -> net_tcp_fastopen_backup_key.sh

kselftests: net_tcp_fastopen_backup_key.sh typo fix up test case name

---

ltp-production.yaml

sysctl02 TFAIL /proc/sys/fs/file-max overflows and is set to 0
ltp-commands-tests/sysctl02_sh failed on 4.19, 4.14, 4.9 and 4.4
Where as it get PASSED on stable rc 5.4 and 5.5 and mainline and linux-next
sysctl02 1 TINFO trying to set fs.file-max=18446744073709551616
sysctl02 1 TFAIL /proc/sys/fs/file-max overflows and is set to 0
Ref:
https://bugs.linaro.org/show_bug.cgi?id=5547

LTP: Adding sysctl02_sh as known failure on 4.19 and older branches

---

ltp-production.yaml

Following known test failures added,
- fgetxattr02
- quotactl01
- copy_file_range02

LTP Adding known issues for juno compat kasan and 64k page size

---

kselftests-production.yaml

kselftests: Adding rtc_rtctest as known intermittent failure

---

ltp-production.yaml

LTP controllers known test failures list added
* memcg_use_hierarchy_test
* memcg_max_usage_in_bytes
* memcg_subgroup_charge

LTP: Adding controllers known test failures

---

ltp-production.yaml

LTP: Adding af_alg02 as know failure on 4.9 and 4.4

---

kvm-unit-tests.yaml
libhugetlbfs-production.yaml
ltp-production.yaml
network-basic-tests.yaml
perf.yaml
spectre-meltdown-checker.yaml
v4l2-compliance.yaml

With new changes in gitlab pipeline the project name
for linux next tree and branch name is master.
- lkft/linux-next-master

LKFT: Add project name linux-next-master

---

kselftests-production.yaml

The test case name use to be like
Directoryname_testcasename
now this has been changed to
Directoryname.testcasename

kselftests: changing testcase name pattern

---

kselftests-production.yaml
kvm-unit-tests.yaml
libhugetlbfs-production.yaml
ltp-production.yaml
network-basic-tests.yaml
perf.yaml
spectre-meltdown-checker.yaml
v4l2-compliance.yaml

Adding new stable rc project name to known issues list
- lkft/linux-stable-rc-linux-5.11.y

project: Adding new project name stable-rc-5.11

---

kselftests-production.yaml
kvm-unit-tests.yaml
libhugetlbfs-production.yaml
ltp-production.yaml
network-basic-tests.yaml
perf.yaml
spectre-meltdown-checker.yaml
v4l2-compliance.yaml

stable-rc 5.8 and stable-rc 5.9 does not existing any more. So
this patch delete those project entries.

Cleanup: Remove old stable rc branches 5.8 and 5.9

---

sync_known_issues.py

This will tell which project an environment is not found
Signed-off-by: Charles Oliveira <charles.oliveira@linaro.org>

sync_known_issues: add project to error log

---

ltp-production.yaml

This will fix our current issue "Incorrect environment for project lkft/linux-next-master: qemu-arm64-debug"

ltp-production: add environments to environments_all

---

packetdrill-tests.yaml

The packetdrill test failures are not stable due to timing errors
timing error: expected inbound packet at 0.201418 sec but happened at 0.205890 sec; tolerance 0.004000 sec
because of above reasons adding all test cases as known failure.

packetdrill: Adding all tests as known failures

---

kselftests-production.yaml
ltp-production.yaml

Adding following qemu environments,
- qemu-i386-clang
- qemu-i386-debug
- qemu-i386-debug-kmemleak
- qemu_x86_64
- qemu-x86_64-clang
- qemu-x86_64-debug
- qemu-x86_64-debug-kmemleak
- qemu-x86_64-kasan
- qemu-x86_64-kcsan
- qemu-arm-clang
- qemu-arm-debug
- qemu-arm-debug-kmemleak
- qemu-arm64-clang
- qemu-arm64-debug
- qemu-arm64-debug-kmemleak
- qemu-arm64-gic-version2
- qemu-arm64-gic-version3
- qemu-arm64-kasan
- qemu-arm64-mte

Adding new qemu environments

---

kselftests-production.yaml

kasan and kcsan were missing for linux-mainline-master

kselftests: Add missing environments to mainline

---

ltp-production.yaml

Add two new environments, trying to keep the environments_all up to
date.
Signed-off-by: Anders Roxell <anders.roxell@linaro.org>

ltp-production: environments_all: add qemu-*debug-kmemleak

---

kselftests-production.yaml
kvm-unit-tests.yaml
libhugetlbfs-production.yaml
ltp-production.yaml
network-basic-tests.yaml

Following obsolete projects have been deleted,
- lkft/linux-stable-rc-linux-5.13.y
- lkft/linux-stable-rc-linux-5.12.y

known issues: Remove obsolete projects

---

kselftests-production.yaml
kvm-unit-tests.yaml
libhugetlbfs-production.yaml
ltp-production.yaml
network-basic-tests.yaml
packetdrill-tests.yaml
perf.yaml
spectre-meltdown-checker.yaml
v4l2-compliance.yaml

New arm64 device bcm2711-rpi-4-b has been added into LKFT LAVA Lab.
This new device added to known issues device type list.

Known-issues: Adding new device type bcm2711-rpi-4-b

---

kselftests-production.yaml
kvm-unit-tests.yaml
libhugetlbfs-production.yaml
ltp-production.yaml
network-basic-tests.yaml
packetdrill-tests.yaml
perf.yaml
spectre-meltdown-checker.yaml
v4l2-compliance.yaml

New arm64 device dragonboard-845c has been added into LKFT LAVA Lab.
This new device added to known issues device type list.

Known-issues: Adding new device type dragonboard-845c

---

ltp-production.yaml

Test names should cope with tuxplan / tuxrun ltp test plans.
This patch removes -tests from the LTP testsuites names.
For examples:
ltp-syscalls-tests replaced by ltp-syscalls
ltp-mm-tests replaced by ltp-mm

LTP: Replace ltp-subtests-test with ltp-subtests

---

kselftests-production.yaml
kvm-unit-tests.yaml
libhugetlbfs-production.yaml
ltp-production.yaml
network-basic-tests.yaml
packetdrill-tests.yaml
perf.yaml
spectre-meltdown-checker.yaml
v4l2-compliance.yaml

Removing obsolete stable-rc 5.17 project.

5.17.y: Removing stable-rc 5.17.y

---

.github/workflows/update-known-issues.yml

Pin github action ubuntu image to ubuntu-20.04
ubuntu-20.04 support python 3.6 which is removed from latest image.

 Pin github action ubuntu image to ubuntu-20.04

---

sync_known_issues.py

Black release 22.12.0 didn't complain. But now with black release 23.1.0, black enforce empty lines before classes and functions with sticky leading comments.

sync_known_issues.py: fix black warning

---

kvm-unit-tests.yaml

We're not testing this combination anymore, which results in an error:
```
Traceback (most recent call last):
File "/home/ddiaz/devel/qa-reports-known-issues/./sync_known_issues.py", line 481, in <module>
main()
File "/home/ddiaz/devel/qa-reports-known-issues/./sync_known_issues.py", line 476, in main
sync_known_issues(config_data, args.dry_run)
File "/home/ddiaz/devel/qa-reports-known-issues/./sync_known_issues.py", line 300, in sync_known_issues
s = SquadProject(project)
File "/home/ddiaz/devel/qa-reports-known-issues/./sync_known_issues.py", line 220, in __init__
SquadKnownIssue(
File "/home/ddiaz/devel/qa-reports-known-issues/./sync_known_issues.py", line 160, in __init__
self._build_environments_set(config)
File "/home/ddiaz/devel/qa-reports-known-issues/./sync_known_issues.py", line …
```

kvm-unit-tests: Drop RPi4 64k-pages

---

android/flakey.txt

which is used by the LKFT Android projects to
define the known flakey tests.
It's in a different format from the current LTS list at moment, which will be changed to the same format in the next step, that the work will be tracked here:
https://linaro.atlassian.net/browse/LCAA-360

Android: initial version of the flakey.txt file

---

kselftests-production.yaml
kvm-unit-tests.yaml
libhugetlbfs-production.yaml
ltp-production.yaml
network-basic-tests.yaml
packetdrill-tests.yaml
v4l2-compliance.yaml

The new stable-rc branch linux-6.8.y is announced.
Adding new project name:
- lkft/linux-stable-rc-linux-6.8.y

Adding new stable-rc branch linux-6.8.y

---

ltp-production.yaml

Re-creating https://github.com/Linaro/qa-reports-known-issues/pull/201 using a branch in this repository

Ltp controller control03
