Linaro/qa-reports-known-issues

ltp-production.yaml

For easy readability new environments have been created and updated.
Following environments have been created
- environments_qemu_all
- environments_qemu_arm_all
- environments_intel_all
- environments_32bit_all
- environments_arm64_arm32

LTP: created and updated environments

---

libhugetlbfs-production.yaml

LKFT: Adding libhugetlbfs known issue list

---

kselftests-production.yaml

LKFT: kselftest: update known failures test case list

---

kselftests-production.yaml
libhugetlbfs-production.yaml
ltp-production.yaml

LKFT: Adding known failure heapshrink-2M-32 on arm32

---

kselftests-production.yaml
libhugetlbfs-production.yaml
ltp-production.yaml

LKFT: Adding new 4.19 tag to known issues

---

kselftests-production.yaml

kselftest: Adding net_pmtu.sh as a known failure

---

README.md
kselftests-production.yaml
sync_known_issues.py
test_data/dupe-issue.yaml
test_data/test-issues.yaml
test_sync_known_issues.py

- Add 'test_names' list field
- Add 'matrix_apply' option
- Add a check to ensure each test is defined once
- Add several tests
- If a project doesn't exist in qa-reports, fail

Features and refactors

---

kselftests-production.yaml

kselftests: cleanup duplicates and maintenance

---

sync_known_issues.py

Deletion respects dry-run, meaning that, if dry run is not used, all
known issues that have a matching 'project' name but are not in the the
yaml file that defines the project will be removed.
Signed-off-by: Dan Rue <dan.rue@linaro.org>

Delete known issues which do not belong

---

kselftests-production.yaml

Signed-off-by: Dan Rue <dan.rue@linaro.org>

x86_fsgsbase_64 fails intermittently

---

kselftests-production.yaml

kselftests: Adding net_test_vxlan_fdb_changelink.sh as known issues

---

ltp-production.yaml

LTP: Adding fs read_all as knonw issue on db410c

---

spectre-meltdown-checker.yaml

spectre-meltdown-checker: Tests are intermittent failures as true

---

kselftests-production.yaml
libhugetlbfs-production.yaml
ltp-production.yaml
spectre-meltdown-checker.yaml

LTP: commands mkswap01_sh failed intermittently

---

ltp-production.yaml

LTP: Update intermittent failures

---

kselftests-production.yaml
ltp-production.yaml

known issues: updating intermittent failure

---

v4l2-compliance.yaml

Adding four known issues and three bugs
- v4l2-compliance/VIDIOC_REQBUFS-CREATE_BUFS-QUERYBUF
- v4l2-compliance/VIDIOC_G-S_PARM
- v4l2-compliance/Cropping
- v4l2-compliance/v4l2-compliance
Ref:
https://bugs.linaro.org/show_bug.cgi?id=4637
https://bugs.linaro.org/show_bug.cgi?id=4638
https://bugs.linaro.org/show_bug.cgi?id=4639

v4l2-compliance: Adding known issues

---

kselftests-production.yaml
libhugetlbfs-production.yaml
ltp-production.yaml
spectre-meltdown-checker.yaml
v4l2-compliance.yaml

The following files have been updated with stable rc 5.1 branch
- kselftests-production.yaml
- libhugetlbfs-production.yaml
- ltp-production.yaml
- spectre-meltdown-checker.yaml
- v4l2-compliance.yaml

known issues: Adding stable rc 5.1 branch to known issues list

---

ltp-production.yaml
spectre-meltdown-checker.yaml

LTP: Adding getrusage04 as known failure on x15 and juno-r2

---

ltp-production.yaml

LTP: Adding ustat02 known failure to arm32

---

kselftests-production.yaml

kselftests: Adding tpm2_test_smoke.sh as known issue

---

ltp-production.yaml

LTP: Adding tgkill03 as known intermittent issue

---

kselftests-production.yaml

kselftests: net: run_netsocktests is not a known issue

---

kselftests-production.yaml
libhugetlbfs-production.yaml
ltp-production.yaml
spectre-meltdown-checker.yaml
test_data/test-issues-2.yaml
test_sync_known_issues.py
v4l2-compliance.yaml

Adding stable-rc 5.2 branch and deleted obsolete 5.0 and 4.20 branches.

stable-rc-5.2: Adding 5.2 branch and remove old branches

---

kselftests-production.yaml

kselftests: Adding known issue timestamping txtimestamp.sh

---

kselftests-production.yaml
libhugetlbfs-production.yaml
ltp-production.yaml
spectre-meltdown-checker.yaml
test_data/test-issues-2.yaml
test_sync_known_issues.py
v4l2-compliance.yaml

stable-rc-5.3: Adding 5.3 branch

---

kselftests-production.yaml
libhugetlbfs-production.yaml
ltp-production.yaml
perf.yaml
spectre-meltdown-checker.yaml
v4l2-compliance.yaml

stable-rc-5.4: Adding new stable branch to known issues list

---

kselftests-production.yaml

kselftest: fix testcase name typo net_traceroute.sh

---

kselftests-production.yaml
libhugetlbfs-production.yaml
ltp-production.yaml
perf.yaml
spectre-meltdown-checker.yaml
v4l2-compliance.yaml

LKFT: Adding nxp-ls2088 device to known issues list

---

ltp-production.yaml

LTP: cve-2017-1000380 Adding as known issue on all devices

---

ltp-production.yaml

LTP: copy_file_range02: Adding as known issue

---

kvm-unit-tests.yaml
ltp-production.yaml

LTP: Adding acct02 as known issue on hikey and db410c devices

---

kselftests-production.yaml
kvm-unit-tests.yaml
ltp-production.yaml
spectre-meltdown-checker.yaml

LKFT: Adding nxp-ls2088 device name to known issues list

---

ltp-production.yaml

Known issues update for compat, kasan and 64k page size failure list.

LTP: known issues update

---

kselftests-production.yaml
kvm-unit-tests.yaml
libhugetlbfs-production.yaml
ltp-production.yaml
perf.yaml
spectre-meltdown-checker.yaml
v4l2-compliance.yaml

LKFT: Adding x86-kasan as new environment

---

kselftests-production.yaml
kvm-unit-tests.yaml
libhugetlbfs-production.yaml
ltp-production.yaml
perf.yaml
spectre-meltdown-checker.yaml
v4l2-compliance.yaml

stable-rc-5.6: Adding new branch 5.6

---

ltp-production.yaml

LTP: Adding juno-r2-compat mode for ltp syscalls

---

perf.yaml

perf: updating known failure test names

---

kselftests-production.yaml
kvm-unit-tests.yaml
libhugetlbfs-production.yaml
ltp-production.yaml
perf.yaml
spectre-meltdown-checker.yaml
v4l2-compliance.yaml

stable-rc-5.7: Adding new branch 5.7

---

kselftests-production.yaml
kvm-unit-tests.yaml
libhugetlbfs-production.yaml
ltp-production.yaml
network-basic-tests.yaml
perf.yaml
spectre-meltdown-checker.yaml
v4l2-compliance.yaml

LKFT: Adding new project stable-rc 5.8

---

kselftests-production.yaml
kvm-unit-tests.yaml
libhugetlbfs-production.yaml
ltp-production.yaml
network-basic-tests.yaml
perf.yaml
spectre-meltdown-checker.yaml
v4l2-compliance.yaml

Adding new environments
Adding new known failures
Adding new intermittent failures 
Removed old projects 5.6 and 5.7

QA reports known issues updates

---

ltp-production.yaml

LTP: Adding dynamic_debug01 as known failure

---

ltp-production.yaml

LTP: Adding known issues on db410c for 4.14 and 4.19

---

ltp-production.yaml

LTP: Adding cpuset_regression_test as known issue on arm32

---

kselftests-production.yaml
kvm-unit-tests.yaml
libhugetlbfs-production.yaml
ltp-production.yaml
network-basic-tests.yaml
perf.yaml
spectre-meltdown-checker.yaml
v4l2-compliance.yaml

kselftests: Adding new branch 5.10 to known issues list

---

ltp-production.yaml

LTP: Adding known issues semctl09

---

ltp-production.yaml

Adding new environments
Adding ioctl09 as known intermittent failure

Qa reports known issues update

---

sync_known_issues.py

sync_known_issues: fix black

---

kselftests-production.yaml
kvm-unit-tests.yaml
libhugetlbfs-production.yaml
ltp-production.yaml
network-basic-tests.yaml
perf.yaml
spectre-meltdown-checker.yaml
v4l2-compliance.yaml

known issues: Adding new stable-rc 5.12 branch

known issues: Adding new stable-rc 5.12 branch

---

kselftests-production.yaml

kselftest: Modifying test case names to match pattern

---

kselftests-production.yaml
kvm-unit-tests.yaml
libhugetlbfs-production.yaml
ltp-production.yaml
network-basic-tests.yaml
packetdrill-tests.yaml
perf.yaml
spectre-meltdown-checker.yaml
v4l2-compliance.yaml

Known-issues: Adding new environment fx700

---

kselftests-production.yaml

kselftests: Delete duplicate entries reuseport_bpf

kselftests: Delete duplicate entries reuseport_bpf

---

kselftests-production.yaml
kvm-unit-tests.yaml
libhugetlbfs-production.yaml
ltp-production.yaml
network-basic-tests.yaml
packetdrill-tests.yaml
perf.yaml
spectre-meltdown-checker.yaml
v4l2-compliance.yaml

Adding new stable rc branch 5.14 as qa reports project name

known issues: Adding new stable rc branch stable-rc-5.14

---

kselftests-production.yaml
kvm-unit-tests.yaml
libhugetlbfs-production.yaml
ltp-production.yaml
network-basic-tests.yaml
packetdrill-tests.yaml
perf.yaml
spectre-meltdown-checker.yaml

Adding new stable rc branch 5.15 as qa reports project name

known issues: Adding new stable rc branch stable-rc-5.15

---

.github/workflows/dry-run.yml
.github/workflows/update-known-issues.yml
perf.yaml

This adds a pipeline that dry-runs the sync script to make sure yaml is OK.

Fix yaml syntax and add pipeline for checking it on PR

---

kselftests-production.yaml
kvm-unit-tests.yaml
libhugetlbfs-production.yaml
ltp-production.yaml
network-basic-tests.yaml
packetdrill-tests.yaml
perf.yaml
spectre-meltdown-checker.yaml
v4l2-compliance.yaml

Adding new project linux-stable-rc-linux-5.17.y for known issues

5.17.y: Adding new project linux-stable-rc-linux-5.17.y

---

kselftests-production.yaml
kvm-unit-tests.yaml
libhugetlbfs-production.yaml
ltp-production.yaml
network-basic-tests.yaml
packetdrill-tests.yaml
perf.yaml
spectre-meltdown-checker.yaml
v4l2-compliance.yaml

Adding new project linux-stable-rc-linux-5.18.y for known issues

5.18.y: Adding new project linux-stable-rc-linux-5.18.y

---

ltp-production.yaml

Signed-off-by: Anders Roxell <anders.roxell@linaro.org>

ltp-production: update to support tuxtest's devices

---

kselftests-production.yaml
kvm-unit-tests.yaml
libhugetlbfs-production.yaml
ltp-production.yaml
network-basic-tests.yaml
packetdrill-tests.yaml
perf.yaml
spectre-meltdown-checker.yaml
v4l2-compliance.yaml

Adding new stable-rc branch as project linux-stable-rc-linux-6.0.y

projects: stable-rc: Adding linux-6.0.y

---

kselftests-production.yaml
kvm-unit-tests.yaml
libhugetlbfs-production.yaml
ltp-production.yaml
network-basic-tests.yaml
packetdrill-tests.yaml
perf.yaml
spectre-meltdown-checker.yaml
v4l2-compliance.yaml

FVP new environment is added to all known issues list.

known-issues: Adding fvp as new environment

---

.github/workflows/update-known-issues.yml

Signed-off-by: Anders Roxell <anders.roxell@linaro.org>

github actions: use ubuntu-latest

---

kselftests-production.yaml
kvm-unit-tests.yaml
libhugetlbfs-production.yaml
ltp-production.yaml
network-basic-tests.yaml
packetdrill-tests.yaml
perf.yaml
spectre-meltdown-checker.yaml
v4l2-compliance.yaml

QA reports updates and clean up
- Adding 6.1
- Deleting 5.18 and 5.19
- Adding bcm2711-rpi-4-b-clang
- Adding bcm2711-rpi-4-b-64k_page_size

Known issues updates

---

kselftests-production.yaml
kvm-unit-tests.yaml
libhugetlbfs-production.yaml
ltp-production.yaml
network-basic-tests.yaml
packetdrill-tests.yaml
perf.yaml
spectre-meltdown-checker.yaml
v4l2-compliance.yaml

Adding new project name:
- lkft/linux-stable-rc-linux-6.3.y

qa-reports-known-issues: Adding new project stable-rc-linux-6.3.y

---

kselftests-production.yaml
kvm-unit-tests.yaml
libhugetlbfs-production.yaml
ltp-production.yaml
network-basic-tests.yaml
packetdrill-tests.yaml
perf.yaml
spectre-meltdown-checker.yaml
v4l2-compliance.yaml

Adding new project name:
- lkft/linux-stable-rc-linux-6.4.y

Adding new project stable-rc-linux-6.4.y

---

kselftests-production.yaml
kvm-unit-tests.yaml
libhugetlbfs-production.yaml
ltp-production.yaml
network-basic-tests.yaml
packetdrill-tests.yaml
perf.yaml
spectre-meltdown-checker.yaml
v4l2-compliance.yaml

Adding new project name:
- lkft/linux-stable-rc-linux-6.5.y

Adding new project stable-rc-linux-6.5.y
